### ISSUE TITLE
No way to assign a profile to a device

### ISSUE THREAD

**Issue by burningthumb** [awiebe/burningthumb-vk-manage#9]
I know you know this and am just raising it for completeness.  There needs to be a way to assign a profile to a device.

**Comment by awiebe** [comment]
That is the next item on my list of tasks but I had to put in a bunch of usability enhancements today.  I've assigned it to you for now,  since I keep getting usability feature requests, if you are unavailable to do it or unable to complete it please say so here and I will bump its priority above those requests.

**Comment by awiebe** [comment]
Feature completed, tested, looks good, but small device pool for testing.

**Comment by burningthumb** [comment]
I’ll add some more devices.

**Comment by awiebe** [comment]
Believed correct, closing.
